---
# ass_converter 配置

ass_style:
    # 字幕样式
    # 冒号前为同传所匹配的前缀词 
    # 冒号后面为字幕样式 直接复制ass文件中的内容即可
    uru: 星熊uru,思源黑体 Heavy,80,&H00A6CF3D,&H00A6CF3D,&H00FFFFFF,&H00A9FFD5,0,0,0,0,100,100,0,0,1,4,2,2,10,10,30,1

# MatsuriICU是否是完整弹幕
# 如果只是同传弹幕需要把这里改成false
matsuriicu_full_danmu: true
